feat: add js minification (uglify)
stormforger/gulp-template pull request #17
Opened 2019-10-23 13:15 UTC by makeros

With minification (and sourcemaps removed) it's 544B vs 4.98kB.
Right now it's not optional but if it makes sense to minify it always then sourcemaps can be removed.

2019-10-23 13:21 UTC, tisba commented
Thank you for your contribution 💕 

Currently source maps are not used yet, so it might make more sense for now to make source maps optional (to save some bytes). That being said, without source map support, an minified test definition would save us a bit of size, but error traces will become next to impossible to decipher :(

Out of curiosity: Are you trying to address a specific problem? Smaller is better, I know, but since the upload using our CLI will be gzipped anyway, so I'm not sure it makes that much of a difference from a user's perspective.

2019-10-23 13:23 UTC, tisba requested changes

2019-10-23 13:23 UTC, tisba commented on .gitignore
> +dist/
Currently we do recommend to checkin the generated test case for easier accountability.

2019-10-23 13:38 UTC, makeros commented
Hi.
I just wanted to save some some bytes ;) But still, gzipped it will be 344B vs 2.28kB.
I will try to enable sourcemaps (even when it's minified).

Another question, did you thought about transform it to a cli tool so that we can install it from npm?

2019-10-25 09:33 UTC, makeros commented
Hi @tisba . Sourcemaps and minifying is right now control by arguments.
I've also changed a little bit the gulpfile 😶

2019-10-25 12:37 UTC, tisba commented
Hey @makeros!

I'll take a closer look at your changeset ASAP.

Please restore the `dist/` content (`.keep`, etc).

The idea regarding npm is to have a very minimal CLI (or maybe our forge CLI does this) to scaffold the structure and a npm package that defines the gulp pipelines etc. This way we can have a simpler path for updating the tooling.

2020-12-15 13:33 UTC, closed without merging